# Navigation Links
main:
  - name: 关于
    url: /
    weight: 10
  - name: 项目
    url: /#projects
    weight: 20
  - name: 视频
    url: /#videos
    weight: 30
  - name: 博客
    url: /#blog
    weight: 40
  - name: 简历
    url: experience/
    weight: 50
  - name: 联系
    url: /#contact
    weight: 60
